'''
Builtin command list for iKonsole.

DO NOT EDIT THIS FILE. This file contains list of all the builtin
commands. Editing may cause instability or problems in some feature.
'''

IKONSOLE_CMD_BUILTIN = ['cd', 'isfile', 'rname', 'showtime', 'simpletext', 'copy']
